### ISSUE TITLE
Docker worker: "TypeError: expected str, bytes or os.PathLike object, not NoneType"

### ISSUE THREAD

**Issue by saulp** [line/promgen#274] opened 2020-04-30 14:46 UTC
Hi Paul,

As of recently, my Promgen instance is failing to write/generate the promgen.json config file.

The below Celery trace can be consistently reproduced by clicking the "Commit" button on the app. 

I'm still trying to figure out what could have changed in my system since the last time it ran without issues, possibly Red Hat package updates. I'm verifying this with my colleagues.

From some googling, it seems it could be due to a Python version mismatch? I tried updating to the latest docker version of promgen after I started getting the issue to see if it would help, but alas the behaviour is the same. Let me know if you'd like me to share the list of python package versions that are installed on this Red Hat server.

Any clues you are able to provide will be welcome. Thanks!

```
[root@[redacted_hostname] ~]# docker run --network="host" --rm -v ~/.config/promgen:/etc/promgen/ -v /etc/prometheus:/etc/prometheus line/promgen worker -A promgen -l info --queues [redacted_IP]

 -------------- celery@[redacted_hostname].[redacted_domain] v4.3.0 (rhubarb)
---- **** -----
--- * ***  * -- Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with 2020-04-30 14:40:05
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         promgen:0x7f4def64eb00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> [redacted_IP]    exchange=[redacted_IP](direct) key=[redacted_IP]
                .> [redacted_hostname].[redacted_domain] exchange=(direct) key=[redacted_hostname].[redacted_domain]

[tasks]
  . promgen.celery.debug_task
  . promgen.tasks.index_alert
  . promgen.tasks.process_alert
  . promgen.tasks.reload_prometheus
  . promgen.tasks.send_alert
  . promgen.tasks.write_config
  . promgen.tasks.write_rules
  . promgen.tasks.write_urls

[2020-04-30 14:40:05,699: INFO/MainProcess] Connected to redis://localhost:6379/0
[2020-04-30 14:40:05,713: INFO/MainProcess] mingle: searching for neighbors
[2020-04-30 14:40:06,725: INFO/MainProcess] mingle: all alone
[2020-04-30 14:40:06,742: INFO/MainProcess] celery@[redacted_hostname].[redacted_domain] ready.
[2020-04-30 14:41:35,261: INFO/MainProcess] Received task: promgen.tasks.write_config[6b58edff-773c-4a46-934b-342c12f94372]
[2020-04-30 14:41:35,271: ERROR/ForkPoolWorker-2] Task promgen.tasks.write_config[6b58edff-773c-4a46-934b-342c12f94372] raised unexpected: TypeError('expected str, bytes or os.PathLike object, not NoneType',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/promgen/tasks.py", line 125, in write_config
    with atomic_write(path, overwrite=True) as fp:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/atomicwrites/__init__.py", line 156, in _open
    with get_fileobject(**self._open_kwargs) as f:
  File "/usr/local/lib/python3.6/site-packages/atomicwrites/__init__.py", line 172, in get_fileobject
    dir = os.path.normpath(os.path.dirname(self._path))
  File "/usr/local/lib/python3.6/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
^C
worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
```

**Comment by saulp** [comment] 2020-04-30 14:49
P.S. I did check that the destination folder and file exist, and that they are writable. Let me know if you'd like me to share a copy of my promgen config.

**Comment by kfdm** [comment] 2020-05-10 23:33
Last week was a holiday in Japan. I will try to triage this today

**Comment by kfdm** [comment] 2020-05-11 07:35
I'm not seeing anything obvious right now. What version are you currently running ?
I think the only changes I've made to the path settings recently were in #183 which was a while back.

**Comment by kfdm** [comment] 2020-05-13 03:04
Seeing a similar error in #276, could you check the path to promtool in your settings ?

```yaml
# Prometheus settings
# These are used for Promgen to automatically trigger a reload on target changes
prometheus:
  url: http://prometheus:9090/
  # Path to promtool to verify valid rules file
  promtool: /usr/local/bin/promtool
```

**Comment by Stroppel** [comment] 2020-05-13 07:52
I have the same problem .. have tried that with 0.44, 0.45.3, latest. Deleted redis multiple times and mysql multiple times. But cant get around that failure. All of that is running in Kubernetes.

**Comment by kfdm** [comment] 2020-05-13 08:06
hmm, perhaps there is a more serious bug in here. Let me see what I can find

**Comment by kfdm** [comment] 2020-05-13 09:04
let me package a new version for you to test. I recently added a `promgen check` command which should help figure out where the issue is

**Comment by kfdm** [comment] 2020-05-13 09:18
I noticed one small bug related to my check scripts, so once that is merged I will cut a new build for testing tomorrow (It is now evening in Japan)

**Comment by Stroppel** [comment] 2020-05-13 09:33
oh thats nice .. thank you

**Comment by kfdm** [comment] 2020-05-14 01:44
I just released a new build of Promgen ( https://github.com/line/promgen/releases/tag/v0.47 )
Can you give that a try? run the `promgen check` command should also check the configuration file and see if it can find the directories it needs and find promtool

**Comment by Stroppel** [comment] 2020-05-14 12:29
thnx.. will try that

**Comment by kfdm** [comment] 2020-05-15 02:44
Yesterday I did one more minor release to fix a different bug, so please try running with 0.47.1

The command should look something like this

`docker run --rm -it -v /path/to/promgen:/promgen:/etc/promgen  line/promgen:v0.47.1 promgen check`

**Closed** 2021-01-18 01:47 UTC
